### ISSUE TITLE
some issues about MRC.ipynb

### ISSUE THREAD

**Issue by Cheng-SQ0716** [ezzini/QAssist#2]
Hello!

I just find some issues running MRC.ipynb in google colab
1. Sometime it reports error: 

* *NotImplementedError: A UTF-8 locale is required.* *

it can be solved by adding these codes at the beginning of the notebook:
`import locale`
`locale.getpreferredencoding = lambda: "UTF-8" # run these codes to solve "A UTF-8 locale is required." issue`

2. in 'Start Elastic Search Server' section, `haystack.telemetry.disable_telemetry() ` is unable to run
try:
`import haystack.telemetry`
`print(dir(haystack.telemetry))`
it shows all of the functions/attributes without disable_telemetry(), but it has .telemetry and .Telemetry

3.in 'prepare data and define metrics' section, unable to run this cell:

`# Connect to Elasticsearch`
`document_store = ElasticsearchDocumentStore(
    host="localhost",
    username="",
    password="",
    index="doc_index",
    label_index="label_index",
    embedding_field="emb",
    embedding_dim=768,
    excluded_meta_data=["emb"],
)`
`#document_store = InMemoryDocumentStore()`

it reports error:
* *ImportError: cannot import name 'Connection' from 'elasticsearch' * *

check the [elasticresearch package codes in line 7](https://github.com/deepset-ai/haystack/blob/main/haystack/document_stores/elasticsearch.py), it requires **Connection** attribute

similarly, attempt:
`import elasticsearch`
`print(dir(elasticsearch))`
the results does not shows 'Connection' 
besides, it seems that 'RequestsHttpConnection' and  'Urllib3HttpConnection' are not in 'elasticsearch', too

This cell also reports two errors:

* *ImportError: Failed to import 'haystack.document_stores.elasticsearch', which is an optional component in Haystack.
Run 'pip install 'farm-haystack[elasticsearch]'' to install the required dependencies and make this component 
available.
(Original error: cannot import name 'Connection' from 'elasticsearch' 
(/usr/local/lib/python3.10/dist-packages/elasticsearch/__init__.py))* *

and 

* *ImportError: Failed to import 'ElasticsearchDocumentStore', which is an optional component in Haystack.
Run 'pip install 'farm-haystack[elasticsearch]'' to install the required dependencies and make this component 
available.
(Original error: Failed to import 'haystack.document_stores.elasticsearch', which is an optional component in 
Haystack.
Run 'pip install 'farm-haystack[elasticsearch]'' to install the required dependencies and make this component 
available.
(Original error: cannot import name 'Connection' from 'elasticsearch' 
(/usr/local/lib/python3.10/dist-packages/elasticsearch/__init__.py)))* *

I guess these are analogus issues

**Comment by ezzini** [comment]
Thanks @Cheng-SQ0716 for the detailed report. 
Most of these issues arise because Haystack has received major updates making most of the code deprecated. 
I will add an exact commit version to the line where I install haystack. This way, I hope it will solve all future deprecation problems.
